click on button copies to clipboard
powercode-boys/digital-macro-pad pull request #16
Opened 2023-01-13 15:50 UTC by Ediz97

Ich hab das Kopieren Feature hinzugefügt, ging sogar relativ schnell und einfach. Abgebrancht wurde von beschreibung-hinzufügen. Falls der Branch nicht mehr existieren sollte, weil er z.B. in den dev-Branch gemerged wurde, muss der Target-Branch vermutlich entsprechend angepasst werden.

2023-01-16 07:40 UTC, Laurenz1606 commented
Wie wäre es mit User-Feedback, als Indikator fürs Kopieren? DaisyUI selber hat keine Notification (Toast) Komponente, aber wie wäre es damit? https://mariojgt.github.io/wind-notify/ baut auf Tailwind und DaisyUI.

2023-01-16 07:46 UTC, Laurenz1606 approved these changes

2023-01-16 07:46 UTC, Laurenz1606 requested changes
siehe Oben

2023-01-16 08:02 UTC, Laurenz1606 commented
https://mariojgt.github.io/wind-notify/ ist buggy, daisyUI hat selber auch eine Toast Komponente, nur ohne message API. https://daisyui.com/components/toast/

2023-01-16 14:43 UTC, LucaBach commented
Pointer beim hovern über das Makro macht nicht so viel Sinn, da nichts passiert wenn man draufdrückt.

2023-01-16 15:28 UTC, Ediz97 commented
done, das Makro an sich muss inzwischen kein Button mehr sein, deshalb hab ich den Button-Tag, der das ganze Makro ummantelt entfernt, und den hovering Effekt auch. Luca und ich sehen da keinen Sinn darin, wenn wir sowieso einen Copy und einen Play Button verwenden. Das Clipping im Title stellt btw auch kein großes Problem dar, da nach Wörtern clippen ganz normal funktioniert, das mit dem Clipping wird nur schwierig wenn ein Wort ca. 20+ Zeichen hat, was nur selten vorkommen sollte^^

2023-01-16 18:24 UTC, Laurenz1606 commented
Okay das klingt doch gut. Ja das mit dem testen war von uns vielleicht nicht so smart das wir immer nur mit einem durchehenden string getestet haben xD Naja nh aber das erklärt auch warum das bei mir dann ging vorhin wo wir die Klassen verglichen haben.

2023-01-17 08:07 UTC, Laurenz1606 approved these changes

2023-01-17 09:56 UTC, MrShipooopi commented
![2023-01-17 10_54_27-Ediz, Laurenz, und Luca _ Microsoft Teams](https://user-images.githubusercontent.com/118967003/212866776-edc17ed3-8c0a-4fac-b65b-7fe899477fc2.png)
Es gibt eine Fenstergröße, wo man ein Makro nicht mehr kopieren kann, weil der Anlegen-Knopf drüber liegt. Müsst ihr entscheiden wie sehr euch das nervt oder nicht, muss für mcih nicht zwangsläufig umgesetzt werden, ist mir nur aufgefallen

2023-01-17 09:56 UTC, MrShipooopi reviewed
Rest passt, könnt ihr ohne weitere Abnahme mergen

2023-01-17 09:56 UTC, MrShipooopi commented on src/svelte/App.svelte
> -    {#if $macroStore.length > 0}
ihr müsst mal eure Tablänge angleichen, irgendwer hat 2 und irgendwer 4, das macht die PRs schwer lesbar

2023-01-17 09:59 UTC, Laurenz1606 commented on src/svelte/App.svelte
> -    {#if $macroStore.length > 0}
Habe meine auf 4 angepasst

2023-01-17 10:00 UTC, merged

2023-01-17 10:01 UTC, Laurenz1606 commented
> ![2023-01-17 10_54_27-Ediz, Laurenz, und Luca _ Microsoft Teams](https://user-images.githubusercontent.com/118967003/212866776-edc17ed3-8c0a-4fac-b65b-7fe899477fc2.png) Es gibt eine Fenstergröße, wo man ein Makro nicht mehr kopieren kann, weil der Anlegen-Knopf drüber liegt. Müsst ihr entscheiden wie sehr euch das nervt oder nicht, muss für mcih nicht zwangsläufig umgesetzt werden, ist mir nur aufgefallen

Haben wir vorhin auch drüber gesprochen, schreibe das als Notiz an unsere Wand mit aber erstmal machen wir am MVP weiter.